### ISSUE TITLE
Ignore namespace

### ISSUE THREAD

**Issue by hpcsc** [state-machines/state_machines-audit_trail#15]
Hi,

Is it possible to not log into `namespace` column if state machine doesn't use it?
My state machine doesn't use namespace, and I already removed the `namespace` column from `StateTransition` class and schema, however when logging's saved, it still looks for `namespace` column and have this error:

```
ActiveRecord::UnknownAttributeError: unknown attribute 'namespace'
```

**Comment by rosskevin** [comment]
We are open to a PR supplied with an additional test.

**Comment by rosskevin** [comment]
If you are going to PR, we can reopen this.
