### ISSUE TITLE
Reconsider use of the 'from' reserved keyword

### ISSUE THREAD

**Issue by SirRawlins** [state-machines/state_machines-audit_trail#17]
Afternoon kind folk,

I've been querying my audit-trail today to find any previous transitions to and from particular states, and I've found myself getting syntax errors because of the use of the 'from' keyword as a column name. This means that queries like this will fail:

```ruby
state_transitions.where('from = ?', 'my_initial_state_name')
```

You then have to implement DB-Specific workarounds into the syntax to get the query running properly, in Postgres for instance, wrapping `from` in double quotes does the trick.

I wonder if we should consider a move away from using reserved words as database column names?

**Comment by sfcgeorge** [comment]
Agreed that a different name would be easier, but if you use AR syntax it just works anyway:

```ruby
state_transitions.where(from: 'my_initial_state_name')
```

**Comment by smudge** [comment]
If you need to reference the column in bare SQL you can include the table it belongs to:

```ruby
state_transitions.where('my_table.from LIKE ?', 'something_%')
```

**Comment by rosskevin** [comment]
This would be a breaking change and I'm not sure the migration pain is warranted.  If there is greater demand I'm happy to reopen this.
