### ISSUE TITLE
Is there a CHANGELOG?

### ISSUE THREAD

**Issue by veganstraightedge** [state-machines/state_machines-audit_trail#40]
If there was a CHANGELOG.md or HISTORY.md or notes on the release page, it'd make it a lot easier/clearer/safer to upgrade the gem when new versions come out. 

Tools like Dependabot automatically use the contents of those files when creating a PR for an upgrade.

For example, in my case Dependabot a PR that upgrades this gem from 1.0.2 to 2.0.2.
But there's no description of what changed in that time. 

Our tests passed, but with major version increases like this, I like to also read the changelog to see if there are any breaking changes or deprecations that I should look out for.

Thanks

**Comment by seuros** [comment]
I just pushed it and added release workflow to have it always updated.
